on: [push]

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}

jobs:
  deploy-game:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Aftman installation
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package installation
        shell: bash
        run: wally install

      - name: Run lune scripts and build rojo
        shell: bash
        run: |
          rojo build default.project.json -o build.rbxlx
          lune run deploy.luau

      - name: Final check
        run: ls
