on: [push]

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
  RBXCLOUDAPI_KEY: ${{ secrets.RBXCLOUDAPI_KEY }}
  UNIVERSE_ID: '5904744525'
  START_PLACE_ID: '17260500381'

jobs:
  deploy-game:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Aftman installation
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package installation
        shell: bash
        run: wally install

      - name: Build rojo place file
        shell: bash
        run: rojo build default.project.json -o build.rbxlx

      - name: Pull in assets using lune
        shell: bash
        run: lune run deploy.luau

      - name: Deploy place file to roblox
        shell: bash
        run: |
          curl --verbose --location POST 'https://apis.roblox.com/universes/v1/${{ env.UNIVERSE_ID }}/places/${{ env.START_PLACE_ID }}/versions?versionType=Published' --header 'x-api-key: ${{ env.RBXCLOUDAPI_KEY }}' --header 'Content-Type: application/xml' --data-binary build.rbxlx
