on: [push]

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
  RBXCLOUDAPI_KEY: ${{ secrets.RBXCLOUDAPI_KEY }}
  UNIVERSE_ID: '5904744525'
  START_PLACE_ID: '17260500381'

jobs:
  deploy-game:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Aftman installation
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package installation
        shell: bash
        run: wally install

      - name: Build rojo place file
        shell: bash
        run: rojo build default.project.json -o build.rbxl

      - name: Pull in assets using lune and deploy to roblox
        shell: bash
        run: lune run deploy.luau
